server:
  port: 8091

spring:
  application:
    name: kgt-feedback
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    driver-class-name: ${FEEDBACK_DATASOURCE_DRIVER}
    url: ${FEEDBACK_DATASOURCE_URL}
    username: ${FEEDBACK_DATASOURCE_USERNAME}
    password: ${FEEDBACK_DATASOURCE_PASSWORD}
  jpa:
    database-platform: ${FEEDBACK_JPA_DATABASE_PLATFORM}
    hibernate:
      ddl-auto: ${FEEDBACK_JPA_HIBERNATE_DDL_AUTO}

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: kgt-gateway

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/