version: '3.3'

services:
  kgt-registry:
    build:
      context: ./kgt-registry/

  kgt-authorization:
    build:
      context: ./kgt-authorization/

  kgt-gateway:
    build:
      context: ./kgt-gateway/

  kgt-ml-prediction:
    build:
      context: ./kgt-ml-prediction/

  kgt-feedback:
    build:
      context: ./kgt-feedback/

  kgt-ontology:
    build:
      context: ./kgt-ontology/

  kgt-react:
    build:
      dockerfile: dev.Dockerfile
      context: ./kgt-react/
    volumes:
      - ./kgt-react:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"