version: '3.3'

services:
  kgt-ml-prediction:
    image: '${IP_ADDR}/kgt/kgt-ml-prediction:latest'
    restart: always
    command: gunicorn --bind 0.0.0.0:5001 manage:app
    container_name: kgt-ml-prediction
    environment:
      - 'FLASK_APP=${FLASK_APP}'
      - 'FLASK_ENV=${FLASK_ENV}'
      - 'APP_FOLDER=${APP_FOLDER}'
